export enum TB_ACCESSORS {
  BRANCH = 'branch',
  CHECKID = 'checkId',
  CODE = 'code',
  COMMIT = 'commit',
  COMPLETED_AT = 'completedAt',
  CREATED_AT = 'createdAt',
  DURATION = 'duration',
  IMAGE = 'imageUrl',
  NAME = 'name',
  PATH = 'path',
  REPOSITORY = 'repository',
  STATUS = 'status',
  STORY = 'story',
}
